name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
      HTTP_PATH: ${{ secrets.HTTP_PATH }}
      DATABRICKS_KEY: ${{ secrets.DATABRICKS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy